// Seatbelt (SBPL) profile generator.
//
// The old bash version baked the profile into a heredoc and patched it with
// sed. Here the profile is assembled from small typed helpers, so the parts
// you actually want to tweak live in config.ts as plain data.

import fs from 'node:fs';
import path from 'node:path';
import { type Config, expandHome, HOME } from '../utils/config.js';

// ---- SBPL helpers ----------------------------------------------------------

// Quote a literal string for SBPL. Only `"` needs escaping; backslashes are
// left as-is so regex patterns survive verbatim.
const q = (s: string): string => `"${String(s).replace(/"/g, '\\"')}"`;

export const subpath = (p: string): string => `(subpath ${q(p)})`;
export const literal = (p: string): string => `(literal ${q(p)})`;
export const regex = (p: string): string => `(regex ${q(p)})`;
export const globalName = (n: string): string => `(global-name ${q(n)})`;
export const ipcName = (n: string): string => `(ipc-posix-name ${q(n)})`;

/** Escape a path for safe embedding inside an SBPL regex. */
export const reEscape = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function block(op: string, rules: string[]): string {
  return [`(${op}`, ...rules.map((r) => `  ${r}`), ')'].join('\n');
}
const allow = (op: string, ...rules: string[]): string => block(`allow ${op}`, rules);
const deny = (op: string, ...rules: string[]): string => block(`deny ${op}`, rules);

// ---- package-manager autodetection ----------------------------------------

/** Detect installed package managers whose paths must be readable/executable. */
export function detectPackagePaths(): string[] {
  const paths: string[] = [];
  if (fs.existsSync('/opt/homebrew')) paths.push('/opt/homebrew');
  else if (fs.existsSync('/usr/local/Homebrew')) paths.push('/usr/local/Homebrew');
  const local = path.join(HOME, '.local');
  if (fs.existsSync(local)) paths.push(local);
  if (fs.existsSync('/nix/store')) paths.push('/nix/store');
  return paths;
}

/** Context needed to assemble a profile for a specific project. */
export interface ProfileContext {
  projectDir: string;
  detectedPaths?: string[];
}

/**
 * Build the full SBPL profile text.
 * @param config  effective config (see config.ts)
 * @param ctx     { projectDir, detectedPaths }
 */
export function buildProfile(
  config: Config,
  { projectDir, detectedPaths = detectPackagePaths() }: ProfileContext,
): string {
  const configDir = expandHome(config.configDir);
  const sshDir = expandHome(config.bot.sshDir);
  const homeRe = reEscape(HOME);

  const sections: string[] = [];
  const add = (comment: string, body: string) => sections.push(`;; ---------- ${comment}\n${body}`);

  sections.push(
    [
      ';; ------------------------------------------------------------------',
      ';;  Claude Code macOS sandbox profile (autogenerated)',
      ';; ------------------------------------------------------------------',
      '(version 1)',
      '(deny default)',
    ].join('\n'),
  );

  add('introspection & sysctl', '(allow file-read-metadata)\n(allow sysctl-read)');

  add(
    'basic dir traversal',
    [
      allow('file-read*', literal('/')),
      allow('file-read*', literal('/private')),
      allow('file-read-data', literal('/Users')),
      allow('file-read-data', literal(HOME)),
    ].join('\n'),
  );

  add(
    'system runtime (read-only)',
    allow(
      'file-read* file-map-executable',
      subpath('/System'),
      subpath('/usr'),
      subpath('/bin'),
      subpath('/sbin'),
      subpath('/Library/Frameworks'),
      subpath('/private/etc'),
      subpath('/var/db/dyld'),
      ...detectedPaths.map(subpath),
    ),
  );

  add(
    'Xcode / Command Line Tools (xcrun, git, etc.)',
    [
      allow(
        'file-read* file-map-executable',
        subpath('/Library/Developer/CommandLineTools'),
        subpath('/Applications/Xcode.app'),
      ),
      allow(
        'process-exec',
        subpath('/Library/Developer/CommandLineTools'),
        subpath('/Applications/Xcode.app'),
      ),
    ].join('\n'),
  );

  // global npm/pipx/cargo bins (user-installed)
  const userPaths = detectedPaths.filter((p) => p.endsWith('/.local'));
  add(
    'global npm/pipx/cargo bins',
    userPaths.length
      ? userPaths.map((p) => allow('file-read*', subpath(p))).join('\n')
      : ';; No user package paths detected',
  );

  add(
    'executable paths',
    allow(
      'process-exec',
      subpath('/usr'),
      subpath('/System'),
      subpath('/bin'),
      subpath('/sbin'),
      literal('/usr/bin/env'),
      ...detectedPaths.map(subpath),
    ),
  );

  add(
    'temp dirs',
    allow(
      'file-read* file-write*',
      subpath('/tmp'),
      subpath('/private/tmp'),
      regex('^/private/var/folders/'),
    ),
  );

  add('Claude config & token files', allow('file-read* file-write*', subpath(configDir)));

  add(
    'Claude auto-update (RO) -- suppress warnings',
    allow(
      'file-read*',
      subpath(path.join(HOME, '.local/state/claude')),
      subpath(path.join(HOME, '.cache/claude')),
    ),
  );

  add(
    'time-zone & prefs (RO)',
    allow('file-read*', subpath('/private/var/db/timezone'), subpath('/Library/Preferences')),
  );

  add(
    '/dev access (RO) + ioctl',
    [
      allow('file-read*', literal('/dev')),
      allow('file-read* file-write*', regex('^/dev/(tty.*|null|zero|dtracehelper)')),
      allow('file-ioctl', literal('/dev/dtracehelper'), regex('^/dev/tty.*')),
    ].join('\n'),
  );

  add(
    'mach-lookup services',
    allow(
      'mach-lookup',
      globalName('com.apple.system.opendirectoryd.libinfo'),
      globalName('com.apple.SystemConfiguration.DNSConfiguration'),
      globalName('com.apple.coreservices.launchservicesd'),
      globalName('com.apple.CoreServices.coreservicesd'),
      globalName('com.apple.system.notification_center'),
      globalName('com.apple.logd'),
      globalName('com.apple.diagnosticd'),
      globalName('com.apple.lsd.mapdb'),
      globalName('com.apple.lsd.modifydb'),
      globalName('com.apple.coreservices.quarantine-resolver'),
      globalName('com.apple.pasteboard.pboard'),
      globalName('com.apple.pasteboard.1'),
    ),
  );

  add(
    'Launch Services needed by /usr/bin/open',
    allow('mach-lookup', regex('^com\\.apple\\.lsd(\\..*)?$')),
  );

  add(
    'Developer Tools (xcrun / libxcrun)',
    allow('mach-lookup', globalName('com.apple.dt.xcsecurity'), regex('^com\\.apple\\.dt\\..*$')),
  );

  add(
    'Audio (afplay)',
    allow(
      'mach-lookup',
      globalName('com.apple.audio.audiohald'),
      globalName('com.apple.audio.AudioComponentRegistrar'),
    ),
  );

  add(
    'Notification Center shared-memory (RO)',
    allow('ipc-posix-shm-read-data', ipcName('apple.shm.notification_center')),
  );

  add(
    'User-level preference reads (RO)',
    allow('file-read*', subpath(path.join(HOME, 'Library/Preferences'))),
  );

  // Keychain RW so Claude can persist refreshed OAuth tokens (else ~24h → 401).
  add(
    'Keychain access (for OAuth)',
    [
      allow('file-read* file-write*', subpath(path.join(HOME, 'Library/Keychains'))),
      allow(
        'mach-lookup',
        globalName('com.apple.SecurityServer'),
        globalName('com.apple.security.agent'),
        globalName('com.apple.securityd'),
        globalName('com.apple.secd'),
        globalName('com.apple.trustd'),
        globalName('com.apple.trustd.agent'),
        globalName('com.apple.CoreAuthentication.daemon'),
      ),
    ].join('\n'),
  );

  add(
    'git config (RO)',
    allow(
      'file-read*',
      literal(path.join(HOME, '.gitconfig')),
      literal(path.join(HOME, '.gitignore_global')),
      subpath(path.join(HOME, '.config/git')),
    ),
  );

  // Soft privacy DENY list — placed BEFORE the extra readOnly/readWrite and the
  // project dir, so an explicit grant may override it (e.g. running on a project
  // that lives under ~/Documents). The hard secret deny below is what's binding.
  const softDeny = [
    ...config.denyHome.map((d) => subpath(path.join(HOME, d))),
    ...config.paths.deny.map((p) => subpath(expandHome(p))),
  ];
  add(
    'soft privacy DENY list (overridable by explicit grants)',
    deny('file-read* file-write*', ...softDeny),
  );

  add(
    'SSH: bot key + known_hosts (personal keys hard-denied at the very end)',
    [
      allow(
        'file-read*',
        literal(path.join(HOME, '.ssh')),
        literal(path.join(HOME, '.ssh/known_hosts')),
        literal(path.join(HOME, '.ssh/known_hosts2')),
        literal(path.join(HOME, '.ssh/config')),
        subpath(sshDir),
      ),
      allow(
        'file-write*',
        literal(path.join(HOME, '.ssh/known_hosts')),
        literal(path.join(HOME, '.ssh/known_hosts2')),
      ),
    ].join('\n'),
  );

  // Extra user-supplied RO / RW / exec rules. Hook scripts that claude must run
  // inside the sandbox are granted via `paths.exec` (read via `paths.readOnly`).
  // Compiled hooks (config.hooks) only register the script with claude — the
  // sandbox still needs an exec grant for the script's path to actually run.
  if (config.paths.readOnly.length)
    add(
      'extra read-only paths',
      allow('file-read*', ...config.paths.readOnly.map((p) => subpath(expandHome(p)))),
    );
  if (config.paths.readWrite.length)
    add(
      'extra read-write paths',
      allow('file-read* file-write*', ...config.paths.readWrite.map((p) => subpath(expandHome(p)))),
    );
  if (config.paths.exec.length)
    add(
      'extra exec paths',
      allow('process-exec', ...config.paths.exec.map((p) => subpath(expandHome(p)))),
    );

  add(
    'project workspace (RW)',
    [
      allow('file-read* file-write* file-map-executable', subpath(projectDir)),
      allow('process-exec', subpath(projectDir)),
    ].join('\n'),
  );

  // Hard secret DENY — emitted LAST of all file rules so it wins even over a
  // broad readOnly/readWrite or the project dir (SBPL = last matching rule
  // wins). This is the binding invariant: personal credentials and private keys
  // are never readable, however wide the grants above. Only the bot key subdir
  // (allowed earlier, and not matched by these patterns) stays readable.
  const hardDeny: string[] = [];
  if (config.denyDotConfigs.length) {
    hardDeny.push(regex(`^${homeRe}/\\.(${config.denyDotConfigs.join('|')})($|/)`));
  }
  hardDeny.push(
    regex(`^${homeRe}/\\.ssh/id_`),
    regex(`^${homeRe}/\\.ssh/.*\\.pem$`),
    regex(`^${homeRe}/\\.ssh/.*\\.key$`),
  );
  add(
    'hard secret DENY (always wins — credentials & private keys)',
    deny('file-read* file-write*', ...hardDeny),
  );

  if (config.network) add('networking', '(allow network*)');

  sections.push('(allow process-fork)\n(allow lsopen)');

  const text = `${sections.join('\n\n')}\n`;

  // Sanity-check before anyone feeds it to sandbox-exec.
  if (!/^\(version 1\)/m.test(text)) {
    throw new Error('generated sandbox profile is missing "(version 1)"');
  }
  return text;
}
