// The shell helpers that make the broker usable by hand: `o .`, `c file`, `ob
// note.md`. Pure — this file only builds text; `server.ts` writes it next to the
// socket and the log, in `<claboxHome>/opener/`.
//
// They talk to the socket DIRECTLY, with `nc -U`, and never run `clabox`. That
// is the point: the wire format is one line (`<action> <absolute path>`), the
// box already has the socket grant, and exec'ing clabox inside a box needs a
// grant on wherever clabox's binary physically resolves — which for a dev
// install (`npm link`) is its own source repo, a path no other box grants. So a
// helper built on `clabox reveal` dies with `operation not permitted: clabox`
// before the socket is ever touched, while `nc` lives in `/usr/bin`, which every
// box can already read and exec.
//
// Why clabox generates this at all instead of documenting it: the correct helper
// is not one line. The broker takes two different verbs depending on whether the
// target is a file or a directory, it only accepts ABSOLUTE paths, and outside a
// box none of it applies and the plain `open` is still what you want.
//
// Shell dialect: POSIX, so the same file sources in bash and zsh. The lines are
// assembled as plain single-quoted strings rather than one template literal on
// purpose — the shell text is full of backticks and parameter expansions, both of
// which would need escaping inside a template literal, i.e. a diff you can't
// read against the file it produces.

/** Basename of the generated helpers file. */
export const ALIASES_FILENAME = 'claude-aliases.sh';

/**
 * The source-able shell helpers, as text.
 *
 * @param socket absolute path of the broker's socket, baked in at generation
 *   time. The file is written per machine into the clabox home, so there is
 *   nothing to gain from re-deriving `<claboxHome>/opener/opener-<uid>.sock` in
 *   shell — and a baked path cannot drift from the broker that wrote it.
 *
 * Deliberately **not** a place for a user's unrelated shell functions: this file
 * is rewritten by every `clabox opener` start, so it holds only what belongs to
 * the opener. Anything personal goes in your own rc, which can `source` this.
 */
export function buildClaudeAliases(socket: string): string {
  return [
    '# Shell helpers for the clabox opener broker — GENERATED by `clabox opener`.',
    '# Rewritten on every broker start: do not edit, source it instead.',
    '#',
    '# Шорткаты bash-режима Claude Code (`!o .`, `!c .`). Подключить —',
    '# одним из двух способов:',
    '#   source ~/.config/clabox/opener/claude-aliases.sh      # в своём .zshrc',
    '#   CLAUDE_ENV_FILE=~/.config/clabox/opener/claude-aliases.sh',
    '# Второй вариант — если claude source-ит файл ПЕРЕД каждой bash-командой.',
    '#',
    '# ФУНКЦИИ, не алиасы: режим `!` запускает НЕинтерактивный shell, где',
    '# zsh-алиасы не раскрываются (именно поэтому `!o .` падал с',
    '# `command not found: o`), а функции работают. Синтаксис POSIX-совместим —',
    '# source-ится и в bash, и в zsh.',
    '#',
    '# ВНУТРИ clabox-бокса родной `open` не работает и не будет: он отдаёт путь',
    '# LaunchServices, а тот запускает цель ВНЕ любого сандбокса (PPID 1, без',
    '# профиля) — поэтому `lsopen` боксу не выдан и `open .` отвечает `-54`.',
    '# Рабочий путь — брокер clabox (`clabox opener --detach`, крутится СНАРУЖИ).',
    '#',
    '# Говорим с ним НАПРЯМУЮ через сокет, без запуска `clabox`: протокол — одна',
    '# строка `<действие> <абсолютный путь>`, сокет боксу выдан, а `nc` лежит в',
    '# /usr/bin, который боксу и так доступен на чтение и запуск. Два действия:',
    '#   reveal <папка>  → Finder (`open -R`, запустить ничего не может)',
    '#   edit   <файл>   → приложение по типу (.md → Typora, .md внутри',
    '#                     Obsidian-vault → Obsidian, картинки/PDF → Preview,',
    '#                     код → Zed/Cursor/VS Code/…)',
    '# Папку в `edit` отдавать нельзя — у неё нет расширения из allowlist,',
    '# ответ будет `denied: file type not allowed`. Отсюда развилка в _cb_open.',
    '',
    '# Мы внутри бокса? Отдельного маркера clabox в env не ставит (`env | grep',
    '# CLABOX` пусто), а /Applications боксу не выдан — это самая дешёвая проба.',
    '_cb_inbox() { [ ! -r /Applications ]; }',
    '',
    '# Абсолютный путь без `realpath` (его нет на части систем, и он не нужен —',
    '# брокер всё равно сам делает realpath и проверяет попадание в roots).',
    '_cb_abs() {',
    '  case "$1" in',
    '    /*) printf %s\\\\n "$1" ;;',
    '    *)  if [ -d "$1" ]; then (cd "$1" && pwd)',
    '        else printf %s/%s\\\\n "$(cd "$(dirname "$1")" 2>/dev/null && pwd)" "$(basename "$1")"',
    '        fi ;;',
    '  esac',
    '}',
    '',
    '# Одна строка в сокет брокера. Он отвечает `ok: <приложение>` или',
    '# `denied: <причина>` и закрывает соединение.',
    '_cb_ask() {',
    `  _cb_s='${socket}'`,
    '  if [ ! -S "$_cb_s" ]; then',
    '    echo "opener: брокер не запущен — снаружи бокса: clabox opener --detach" >&2',
    '    return 1',
    '  fi',
    '  printf "%s %s\\n" "$1" "$(_cb_abs "$2")" | nc -U "$_cb_s"',
    '}',
    '',
    '# Открыть путь(и) правильным способом. Вне бокса — ровно как без clabox.',
    '_cb_open() {',
    '  local t',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: shell parameter expansion ("no args → `.`"), not a JS placeholder
    '  for t in "${@:-.}"; do',
    '    if ! _cb_inbox; then',
    '      open "$t"',
    '    else',
    '      case "$t" in',
    '        # Брокер принимает только абсолютные пути; URL из бокса не открыть.',
    '        *://*) open "$t" ;;',
    '        *)',
    '          if [ -d "$t" ]; then _cb_ask reveal "$t"',
    '          else                 _cb_ask edit "$t"',
    '          fi ;;',
    '      esac',
    '    fi',
    '  done',
    '}',
    '',
    'o()   { _cb_open "$@"; }             # o .   → Finder/файл/URL (Open)',
    'щ()   { _cb_open "$@"; }             # щ .   → то же, кириллица',
    'o.()  { _cb_open .; }                # o.    → текущая папка в Finder',
    'щ.()  { _cb_open .; }                # щ.    → то же, кириллица',
    'щю()  { _cb_open .; }                # щю    → o. целиком на кириллице',
    '',
    '# `code` в боксе нет на PATH вообще (`command -v code` пусто), а выбрать',
    '# ИМЕННО VS Code через брокер нельзя: приложение выбирает он — это и есть то',
    '# свойство, из-за которого брокер безопасен. Поэтому в боксе `c` открывает',
    '# тем же роутингом и честно печатает, чем открыл (`ok: Zed`).',
    'c()   { if command -v code >/dev/null 2>&1; then code "$@"; else _cb_open "$@"; fi; }',
    'с()   { c "$@"; }                    # с .   → то же, кириллица',
    'c.()  { c .; }                       # c.    → текущая папка в VS Code',
    'сю()  { c .; }                       # сю    → то же, кириллица',
    '',
    '# obsidian-zen дёргает obsidian:// через LaunchServices — в боксе тот же',
    '# запрет. Но `.md` внутри vault брокер и так отдаёт Obsidian, так что в боксе',
    '# хватает _cb_open.',
    'ob()  { if _cb_inbox; then _cb_open "$@"; else npx obsidian-zen open "$@"; fi; }',
    'щи()  { ob "$@"; }                   # щи    → то же, кириллица',
    'ob.() { ob .; }                      # ob.   → текущая папка',
    'щию() { ob .; }                      # щию   → то же, кириллица',
    '',
  ].join('\n');
}
