// Pure builder for the shell aliases emitted by `clabox init`.
//
// For each box config (`<name>.mjs` / `<name>.config.mjs`) it produces one
// command `clabox-<name>` that runs that box. Whether it runs yolo or asks for
// confirmation is decided by the box's own preset (its `claudeArgs`), not here.
// Plus an `index.sh` defining them all as shell functions to `source`.

import path from 'node:path';

/** A file to be written by `clabox init`. */
export interface InitFile {
  /** Absolute path to write. */
  path: string;
  /** File contents. */
  content: string;
  /** Whether to `chmod +x` after writing. */
  executable: boolean;
}

/** Absolute locations for the generated artifacts. */
export interface AliasPaths {
  /** Dir holding the box config files. */
  configsDir: string;
  /** Dir to emit `index.sh` and the per-box wrappers into. */
  scriptsDir: string;
}

/** The `clabox-<name>` command name for a box. */
export function aliasName(profile: string): string {
  return `clabox-${profile}`;
}

/** Build the source-able `index.sh` defining one function per box. */
export function buildIndex(profiles: string[], { configsDir, scriptsDir }: AliasPaths): string {
  const indexPath = path.join(scriptsDir, 'index.sh');
  const usage = profiles.map((p) => `#   ${aliasName(p)}`);
  const defs = profiles.map((p) => `${aliasName(p)}() { _clabox_run ${p} "$@"; }`);
  return `${[
    '#!/usr/bin/env bash',
    '# Generated by `clabox init` — do not edit; rerun it after changing the configs dir.',
    '#',
    '# Source this from ~/.zshrc or ~/.bashrc:',
    `#   source ${indexPath}`,
    '#',
    "# Commands (run from any cwd). yolo vs. safe is set by each box's preset:",
    ...usage,
    '',
    '_clabox_run() {',
    // Point `-b` at this dir so resolveBox picks the right .mjs/.config.mjs file.
    `  CLABOX_CONFIGS_DIR="${configsDir}" clabox -b "$1" "\${@:2}"`,
    '}',
    '',
    ...defs,
  ].join('\n')}\n`;
}

/** Build a standalone wrapper script that sources `index.sh` and calls one fn. */
export function buildWrapper(fnName: string, indexPath: string): string {
  return `${[
    '#!/usr/bin/env bash',
    '# Generated by `clabox init`.',
    'set -euo pipefail',
    `source "${indexPath}"`,
    `${fnName} "$@"`,
  ].join('\n')}\n`;
}

/** All files `clabox init` writes: the `index.sh` plus a wrapper per box. */
export function buildAliasFiles(profiles: string[], paths: AliasPaths): InitFile[] {
  const indexPath = path.join(paths.scriptsDir, 'index.sh');
  const files: InitFile[] = [
    { path: indexPath, content: buildIndex(profiles, paths), executable: true },
  ];
  for (const p of profiles) {
    const fn = aliasName(p);
    files.push({
      path: path.join(paths.scriptsDir, `${fn}.sh`),
      content: buildWrapper(fn, indexPath),
      executable: true,
    });
  }
  return files;
}
