// Pure builders for the Ghostty-app artifacts emitted by `clabox init`.
//
// For a box that opts in via `app` (see AppConfig), `init` generates a Ghostty
// config whose `command` launches `clabox -b <box>`, then clones Ghostty.app
// with a tiny C launcher that bakes in `--config-file=<that config>`. Everything
// here is text-only (no I/O) so it can be unit-tested without macOS; the actual
// build lives in init/app.ts.

import path from 'node:path';
import type { AppConfig } from '../utils/config.js';

/** Inputs for {@link buildGhosttyConfig} (all paths already absolute). */
export interface GhosttyConfigOptions {
  app: AppConfig;
  /** The `-b` box name this config launches. */
  boxName: string;
  /** Absolute project dir to `cd` into. null → don't `cd` (run in launch cwd). */
  projectDir: string | null;
  /** Absolute `CLABOX_CONFIGS_DIR` so `-b` resolves the box from any cwd. */
  configsDir: string;
  /** Absolute path to the `clabox` binary. */
  claboxBin: string;
  /** Absolute path to a base Ghostty config, emitted as a leading `config-file`. */
  baseGhosttyConfig?: string | null;
}

/** The `command = zsh -lic '…'` line that boots clabox for the box. */
export function buildCommand(opts: GhosttyConfigOptions): string {
  const cd = opts.projectDir ? `cd ${opts.projectDir} && ` : '';
  const inner = `${cd}CLABOX_CONFIGS_DIR=${opts.configsDir} ${opts.claboxBin} -b ${opts.boxName}; exec zsh`;
  // Login + interactive zsh so the GUI-launched app inherits the user's PATH
  // (/etc/zprofile→path_helper for Homebrew, ~/.zshrc for fnm/nvm/volta). A bare
  // `bash -c` gets only launchd's minimal PATH and can't find `node` (clabox's
  // shebang is `#!/usr/bin/env node`).
  return `command = zsh -lic '${inner}'`;
}

/** Build the Ghostty config text for an app box. */
export function buildGhosttyConfig(opts: GhosttyConfigOptions): string {
  const { app } = opts;
  const lines: string[] = [
    '# Generated by `clabox init` — do not edit; rerun it after changing the box config.',
  ];
  if (opts.baseGhosttyConfig) lines.push(`config-file = ${opts.baseGhosttyConfig}`);
  lines.push('', `title = "${app.title ?? app.name}"`);
  if (app.macosIcon) lines.push(`macos-icon = ${app.macosIcon}`);
  if (app.ghostty && Object.keys(app.ghostty).length > 0) {
    lines.push('');
    for (const [key, value] of Object.entries(app.ghostty)) lines.push(`${key} = ${value}`);
  }
  lines.push('', buildCommand(opts));
  return `${lines.join('\n')}\n`;
}

/** Escape a string for embedding as a C double-quoted literal. */
function cEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Build the C launcher source. It finds itself, locates `ghostty.real` next to
 * it, and re-execs it with `--config-file=<configPath>` prepended — so the clone
 * always boots with its own config regardless of how it's launched.
 */
export function buildLauncherSource(configPath: string): string {
  return `// Generated by clabox init. Launches ghostty.real with a baked config.
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <libgen.h>
#include <mach-o/dyld.h>

static const char *CONFIG_PATH = "${cEscape(configPath)}";

int main(int argc, char *argv[]) {
    char path[4096];
    uint32_t size = sizeof(path);
    _NSGetExecutablePath(path, &size);

    char *dir = dirname(path);
    char real_path[4096];
    snprintf(real_path, sizeof(real_path), "%s/ghostty.real", dir);

    char config_arg[4096];
    snprintf(config_arg, sizeof(config_arg), "--config-file=%s", CONFIG_PATH);

    char **new_argv = malloc(sizeof(char *) * (argc + 2));
    new_argv[0] = real_path;
    new_argv[1] = config_arg;
    for (int i = 1; i < argc; i++) new_argv[i + 1] = argv[i];
    new_argv[argc + 1] = NULL;

    execv(real_path, new_argv);
    return 1;
}
`;
}

/** Absolute path to the built `.app` bundle. */
export function appBundlePath(appsDir: string, app: AppConfig): string {
  return path.join(appsDir, `${app.name}.app`);
}

/** Bundle identifier for the clone (explicit, or derived from the box name). */
export function bundleId(boxName: string, app: AppConfig): string {
  return app.bundleId ?? `com.ghostty.custom.${boxName.replace(/-/g, '.')}`;
}
