// Pure builder for the Raycast script commands emitted by `clabox init`.
//
// For each `app` box, `init` writes a Raycast script command (`@raycast.*`
// metadata + `open <app>`) so the built bundle is launchable from Raycast —
// modelled on the hand-written ghostty-*.sh examples. Text only; the fs I/O
// lives in init/scaffold.ts.

import type { AppConfig } from '../utils/config.js';

/** Inputs for {@link buildRaycastCommand}. */
export interface RaycastCommandOptions {
  app: AppConfig;
  /** Absolute path to the built `.app` to open. */
  appPath: string;
}

/** Single-quote a string for safe use in a POSIX shell. */
function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Flatten a value that goes into a `# @raycast.*` **comment** line.
 *
 * A comment is only a comment until the first newline: a `title` containing one
 * would end the comment and leave the rest as a shell statement in a script
 * Raycast runs (outside any sandbox, at the user's click). Quoting can't help
 * here — the value isn't in a string — so control characters are dropped and
 * the line stays one line. Matches `applescript.ts#asQuote`, which drops rather
 * than escapes for the same reason.
 */
function oneLine(s: string): string {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: stripping them is the fix
  return s.replace(/[\r\n\0\x1b]+/g, ' ').trim();
}

/**
 * The Raycast command icon: explicit `app.emoji`, else the title's leading
 * token when it isn't plain ASCII (i.e. an emoji), else the Ghostty 👻.
 */
export function raycastIcon(app: AppConfig): string {
  if (app.emoji) return app.emoji;
  const lead = (app.title ?? '').split(' ')[0];
  // biome-ignore lint/suspicious/noControlCharactersInRegex: ASCII-range guard
  if (lead && !/^[\x00-\x7F]*$/.test(lead)) return lead;
  return '👻';
}

/** Build a Raycast script command that opens the box's built app. */
export function buildRaycastCommand({ app, appPath }: RaycastCommandOptions): string {
  const title = oneLine(app.title ?? app.name);
  return `${[
    '#!/bin/bash',
    '# Generated by `clabox init`.',
    '',
    '# @raycast.schemaVersion 1',
    `# @raycast.title ${title}`,
    '# @raycast.mode silent',
    `# @raycast.icon ${oneLine(raycastIcon(app))}`,
    '# @raycast.packageName Ghostty',
    `# @raycast.description Open ${oneLine(app.name)} with Claude Code in Ghostty (clabox)`,
    '',
    `open ${shellQuote(appPath)}`,
  ].join('\n')}\n`;
}
