// Pure builder for the Raycast script commands emitted by `clabox init`.
//
// For each `app` box, `init` writes a Raycast script command (`@raycast.*`
// metadata + `open <app>`) so the built bundle is launchable from Raycast —
// modelled on the hand-written ghostty-*.sh examples. Text only; the fs I/O
// lives in init/scaffold.ts.

import type { AppConfig } from '../utils/config.js';

/** Inputs for {@link buildRaycastCommand}. */
export interface RaycastCommandOptions {
  app: AppConfig;
  /** Absolute path to the built `.app` to open. */
  appPath: string;
}

/** Single-quote a string for safe use in a POSIX shell. */
function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * The Raycast command icon: explicit `app.emoji`, else the title's leading
 * token when it isn't plain ASCII (i.e. an emoji), else the Ghostty 👻.
 */
export function raycastIcon(app: AppConfig): string {
  if (app.emoji) return app.emoji;
  const lead = (app.title ?? '').split(' ')[0];
  // biome-ignore lint/suspicious/noControlCharactersInRegex: ASCII-range guard
  if (lead && !/^[\x00-\x7F]*$/.test(lead)) return lead;
  return '👻';
}

/** Build a Raycast script command that opens the box's built app. */
export function buildRaycastCommand({ app, appPath }: RaycastCommandOptions): string {
  const title = app.title ?? app.name;
  return `${[
    '#!/bin/bash',
    '# Generated by `clabox init`.',
    '',
    '# @raycast.schemaVersion 1',
    `# @raycast.title ${title}`,
    '# @raycast.mode silent',
    `# @raycast.icon ${raycastIcon(app)}`,
    '# @raycast.packageName Ghostty',
    `# @raycast.description Open ${app.name} with Claude Code in Ghostty (clabox)`,
    '',
    `open ${shellQuote(appPath)}`,
  ].join('\n')}\n`;
}
