// Public API aggregator for clabox — re-exports the config loader, the SBPL
// profile builder and the sandbox launcher so the package can be used as a
// library, not just the `clabox` CLI.

export {
  buildDaemonArgs,
  buildDaemonEnv,
  type DaemonOptions,
  type DaemonResult,
  DEFAULT_DAEMON_ARGS,
  daemonLogPath,
  runDaemon,
} from './daemon/daemon.js';
export {
  type ClaboxPackage,
  claboxVersion,
  type FormatInfoOptions,
  formatInfo,
  type GatherInfoOptions,
  gatherInfo,
  type InfoData,
  resolveClaboxPackage,
} from './info/info.js';
export {
  type AliasPaths,
  aliasName,
  buildAliasFiles,
  buildIndex,
  buildWrapper,
  type InitFile,
} from './init/aliases.js';
export {
  type BuildAppOptions,
  type BuildAppResult,
  buildApp,
  canBuildApps,
  conflictingUserConfig,
  validateGhosttyConfig,
} from './init/app.js';
export {
  appBundlePath,
  assertSafeAppName,
  assertSingleLine,
  type BoxCommandOptions,
  buildCommand,
  buildGhosttyConfig,
  buildHomeConfigShim,
  buildShellCommand,
  bundleId,
  GHOSTTY_APP_DEFAULTS,
  GHOSTTY_SECURITY_DEFAULTS,
  type GhosttyConfigOptions,
  ghosttyHomeConfigPath,
  ghosttyHomeDir,
} from './init/ghostty.js';
export {
  buildRaycastCommand,
  type RaycastCommandOptions,
  raycastIcon,
} from './init/raycast.js';
export {
  type BuiltApp,
  discoverProfiles,
  type InitOptions,
  type InitResult,
  runInit,
} from './init/scaffold.js';
export {
  type AppleScriptResult,
  asQuote,
  buildOpenScript,
  GHOSTTY_BUNDLE_ID,
  type OpenSurfaceOptions,
  runAppleScript,
  SPLIT_DIRECTIONS,
  type SplitDirection,
  type SurfaceMode,
} from './sandbox/applescript.js';
export {
  type BoxExtras,
  boxSlug,
  buildBoxExtras,
  type ExtraFile,
} from './sandbox/extras.js';
export {
  BELL,
  buildNotifyHooks,
  defaultNotifyTitle,
  mergeHooks,
  NOTIFY_TTY,
  notifySeq,
  PROGRESS_STATES,
  type ProgressState,
  progressSeq,
  sanitizeOscText,
  ttyWrite,
} from './sandbox/notify.js';
export {
  ensureProcTools,
  needsRefresh,
  PROC_TOOLS,
  type ProcTool,
  type ProcToolResult,
} from './sandbox/proctools.js';
export {
  buildProfile,
  detectPackagePaths,
  globalName,
  ipcName,
  literal,
  type ProfileContext,
  reEscape,
  regex,
  subpath,
  target,
} from './sandbox/profile.js';
export {
  buildProfileText,
  generateProfile,
  profilePath,
  type RunOptions,
  resolveClaudeBin,
  resolveProjectDir,
  runClaude,
  which,
} from './sandbox/run.js';
export {
  buildTabDecor,
  normalizeColor,
  shortenHome,
  type TabDecor,
  type TabDecorOptions,
  tabTitle,
} from './sandbox/tab.js';
export {
  MUTE_ARGS,
  NO_GUARD,
  type SttyIo,
  sttyIo,
  suppressEcho,
  type TtyGuard,
} from './sandbox/tty.js';
export {
  type AppBuilderConfig,
  type AppConfig,
  assertConfigNotBoxWritable,
  assertSafeBoxName,
  type BotConfig,
  boxWritableRoots,
  type Config,
  claboxBinDir,
  claboxHomeDir,
  configsDir,
  DEFAULT_DENY_WRITE_GLOBS,
  defaultConfig,
  expandHome,
  FLAG_FETCH_BLOCKERS,
  findConfigFile,
  HOME,
  isSafeBoxName,
  type LoadConfigOptions,
  type LoadedConfig,
  listBoxes,
  loadConfig,
  type McpServer,
  mergeConfig,
  type NotifyConfig,
  type OpenerConfig,
  openerAliasesPath,
  openerDir,
  openerLogPath,
  openerPidPath,
  openerSocketPath,
  type PathRules,
  PRIVATE_SYMLINK_ROOTS,
  projectDirOf,
  resolveBox,
  resolvedOpener,
  resolvedTwin,
  type TabConfig,
  withExtraEnv,
  withExtraPaths,
} from './utils/config.js';
export {
  assertConfigTrusted,
  configTrustState,
  hashFile,
  isInside,
  listTrusted,
  readTrustStore,
  type TrustCheckOptions,
  type TrustRecord,
  type TrustState,
  trustConfig,
  trustFilePath,
  untrustConfig,
} from './utils/trust.js';
